name: gnews
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  apple_sign_in: ^0.1.0
  cached_network_image: ^3.0.0-nullsafety
  clippy_flutter: ^2.0.0-nullsafety.1
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  fading_edge_scrollview: ^2.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  firebase_remote_config: ^0.9.0-dev.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_mobx: ^1.0.0
  flutter_tts: ^3.0.0
  flutter_vector_icons: ^1.0.0
  geolocator: ^7.0.1
  google_fonts: 2.0.0
  google_mobile_ads: ^0.11.0+3
  google_sign_in: ^5.0.0
  html: ^0.15.0
  http: ^0.13.0
  image_picker: ^0.7.2+1
  intl: ^0.17.0
  mobx: 1.2.1+3
  nb_utils: ^4.0.8
  onesignal_flutter: ^2.6.1
  osm_nominatim: ^2.0.0
  otp_text_field: ^1.0.2
  package_info: ^2.0.0
  photo_view: ^0.11.1
  share: ^2.0.1
  shimmer: ^2.0.0-nullsafety.0
  story_view: ^0.13.0-nullsafety.1
  url_launcher: ^6.0.2
  video_player: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  flutter_launcher_icons: "^0.9.0"
  mobx_codegen: 1.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoNews.png"
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - lang/
